<a href="https://colab.research.google.com/github/GuptaNavdeep1983/DeepLearningRepo/blob/main/TensorFlow2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Additional References

https://www.toptal.com/python/gradient-descent-in-tensorflow

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3])
b = tf.constant([1,2,3])
c = a + b
d = tf.add(a,b)

print("c:", c)
print("d:", d)

c: tf.Tensor([2 4 6], shape=(3,), dtype=int32)
d: tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [3]:
a = tf.constant([1,2,3])
b = tf.constant([1,2,3])
c = a * b
d = tf.multiply(a, b)

print("c:", c)
print("d:", d)

c: tf.Tensor([1 4 9], shape=(3,), dtype=int32)
d: tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [4]:
a = tf.constant(2.0)

b = tf.math.exp(a)

print("b:", b)

b: tf.Tensor(7.389056, shape=(), dtype=float32)


In [9]:
a_py = [1, 2] 
b_py = [3, 4] 
tf.add(a_py, b_py)

# numpy arrays
a_np = np.array([1, 2])
b_np = np.array([3, 4])

tf.add(a_np, b_np) 

# native TF tensor
a_tf = tf.constant([1, 2])
b_tf = tf.constant([3, 4])

tf.add(a_tf, b_tf)

a_tf.numpy()

array([1, 2], dtype=int32)

In [10]:
X = tf.constant(range(10), dtype=tf.float32)
Y = 2 * X + 10

print("X:{}".format(X))
print("Y:{}".format(Y))

X:[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Y:[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]


In [11]:
X_test = tf.constant(range(10, 20), dtype=tf.float32)
Y_test = 2 * X_test + 10

print("X_test:{}".format(X_test))
print("Y_test:{}".format(Y_test))

X_test:[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Y_test:[30. 32. 34. 36. 38. 40. 42. 44. 46. 48.]


In [13]:
y_mean = Y.numpy().mean()


def predict_mean(X):
    y_hat = [y_mean] * len(X)
    return y_hat

Y_hat = predict_mean(X_test)
print(Y_hat)

[19.0, 19.0, 19.0, 19.0, 19.0, 19.0, 19.0, 19.0, 19.0, 19.0]


In [17]:
errors = (Y_hat - Y)**2
print(errors)
loss = tf.reduce_mean(errors)
print(loss.numpy())

tf.Tensor([81. 49. 25.  9.  1.  1.  9. 25. 49. 81.], shape=(10,), dtype=float32)
33.0


In [ ]:
def loss_mse(X, Y, w0, w1):
    Y_hat = w0 * X + w1
    errors = (Y_hat - Y)**2
    return tf.reduce_mean(errors)